### ISSUE TITLE
Add session label option to bee_track

### ISSUE THREAD

**Issue by lionfish0** [SheffieldMLtracking/bee_track#12] opened 2024-06-10 10:23 UTC
A quick (slightly hacky) solution is to:
- Require that future labels are of the form "setname,sessionid", for example "lf2,session4"
- In [this issue](https://github.com/SheffieldMLtracking/bee_track/issues/9) we then just need to split the label by comma and use the first part for the set and second part for the session (e.g. when making the folders).

Otherwise we need to do all this...
-  Add session variable (copy how 'label' is done) to the backend.
-  Need Flask API endpoint to set (and get?) again copy how the label is done
-  Need change to front end to add way for users to edit.
-  Need to be able to set ALL the systems to the same session id. This might need a change to the interface on michaeltsmith.org.uk
-  
![image](https://github.com/SheffieldMLtracking/bee_track/assets/7914304/de15fe0a-5f06-4f3b-b149-19eb6cbe4bf2)

Note:
I can't remember why, I think because an empty string was a bit awkward to send over the "POST" request, but the code for labels currently prefixes the label with a character on the web interface that is then ignored on the server. (this might be confusing hence why I'm telling you!).

**Comment by Aplefen1** [comment] 2024-06-10 14:51
The issue is addressed in [this commit](https://github.com/SheffieldMLtracking/bee_track/commit/7dde397c087407b5a46fae6a8cf29aecab6e21a0) on the file_sys branch

Photos are now saved in the following file format:

`/home/pi/beephotos/<session>/<set>/<dev_id>/<camid>/<triggertime>____<photoid>.np`

On the frontend you can specify a session and set name by inputting `session,set` into the label field

**Closed** 2024-06-12 11:51 UTC
